### ISSUE TITLE
KeyError when underlying HTTP response is received

### ISSUE THREAD

**Issue by thanatos** [etataurov/asyncio-apns#16]
I'm getting the following traceback when trying to essentially follow the minimal example from the README:

```
» venv/bin/python test_justin.py
Exception in callback _SelectorSocketTransport._read_ready()
handle: <Handle _SelectorSocketTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/selector_events.py", line 730, in _read_ready
    self._protocol.data_received(data)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/sslproto.py", line 514, in data_received
    self._app_protocol.data_received(chunk)
  File "/Users/roy/tmp/apns/venv/lib/python3.6/site-packages/asyncio_apns/h2_client.py", line 101, in data_received
    self.handle_response(event.stream_id)
  File "/Users/roy/tmp/apns/venv/lib/python3.6/site-packages/asyncio_apns/h2_client.py", line 204, in handle_response
    status_code = int(headers[":status"])
```

If I set a breakpoint at that location, `headers`, somewhat oddly, seems to contain bytestrings:

```
» venv/bin/python test_justin.py
> /Users/roy/tmp/apns/test_justin.py(12)send_push()
     11     import ipdb; ipdb.set_trace()
---> 12     apns = await connect(CERT_FILE, KEY_FILE, development=True, loop=loop)
     13     result = await apns.send_message(message, token)

ipdb> b /Users/roy/tmp/apns/venv/lib/python3.6/site-packages/asyncio_apns/h2_client.py:204
Breakpoint 1 at /Users/roy/tmp/apns/venv/lib/python3.6/site-packages/asyncio_apns/h2_client.py:204
ipdb> c
> /Users/roy/tmp/apns/venv/lib/python3.6/site-packages/asyncio_apns/h2_client.py(204)handle_response()
    203         data = data_event.data if data_event is not None else None
1-> 204         status_code = int(headers[":status"])
    205         if status_code != 200:

ipdb> p headers
{b':status': b'200', b'apns-id': b'< redacted >'}
```

…which is weird. I would expect an HTTP library to decode the received headers into strings (`str`) since that's the appropriate data type for that. (That is, `headers` seems to not be decoded enough; the code seems correct to reference the header as `':status'`)

**Comment by etataurov** [comment]
Hi! Thanks for the report.
Could you please verify that it works with `pip install h2==2.6.2` ?
